'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ChevronRight, CircleAlert, Clock3, Copy, Database, FileCode2, GitCommitHorizontal, ListTree, Play, RefreshCw, ShieldAlert, Workflow } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { InvestigationCodeViewer } from '@/components/investigation-code-viewer';
import { fetchInvestigation, reinvestigate, type InvestigationDetail, type InvestigationStageStatus } from '@/lib/api';
import { Link, useRouter } from '@/lib/navigation';

const STAGE_LABELS = { ingest: '接入校验', plan: '采集计划', source: '源码证据', observability: '可观测性', dependencies: '依赖服务', reasoning: '归因推理', resolution: '处置方案' } as const;
const SOURCE_LABELS: Record<string, string> = { alert: '告警', git: 'Git', loki: 'Loki', prometheus: 'Prometheus', tempo: 'Tempo', postgres: 'PostgreSQL', redis: 'Redis', kafka: 'Kafka', clickhouse: 'ClickHouse' };
const OPERATION_LABELS: Record<string, string> = { stage_execution: '阶段执行', repository_discovery: '发现仓库', search_terms: '提取检索关键词', git_clone: '拉取源码', git_fetch: '拉取固定版本', git_checkout: '检出源码版本', context_discovery: '发现仓库上下文', context_read: '读取仓库文档', source_search: '检索源码', source_archive: '归档源码证据', source_diff: '生成版本差异', connector_collection: '采集连接器证据', evidence_freeze: '冻结可引用证据', ai_reasoning: '执行归因推理', remediation_generation: '生成处置方案' };

function tone(status: string) { if (status === 'succeeded' || status === 'completed' || status === 'resolved') return 'ok'; if (status === 'partial' || status === 'blocked' || status === 'not_configured' || status === 'needs_review') return 'warn'; if (status === 'failed') return 'error'; return 'pending'; }
function duration(start: string | null, end: string | null) { if (!start) return '未开始'; if (!end) return '执行中'; const seconds = Math.max(0, Math.round((Date.parse(end) - Date.parse(start)) / 1000)); return seconds < 60 ? `${seconds} 秒` : `${Math.floor(seconds / 60)} 分 ${seconds % 60} 秒`; }
function time(value: string | null | undefined) { return value ? new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(new Date(value)) : '未记录'; }
function stageText(status: InvestigationStageStatus) { return ({ queued: '等待中', running: '执行中', succeeded: '完成', partial: '部分完成', blocked: '已阻断', failed: '失败', not_configured: '未配置' } as Record<InvestigationStageStatus, string>)[status]; }
function operationText(status: string) { return status === 'running' ? '执行中' : stageText(status as InvestigationStageStatus); }
function Status({ status, children }: { status: string; children?: React.ReactNode }) { return <span className={`investigation-status investigation-status-${tone(status)}`}><i />{children ?? status}</span>; }
function EvidenceRefs({ refs, onOpen }: { refs: number[]; onOpen?: (id: number) => void }) { return refs.length ? <span className="investigation-refs">{refs.map((ref) => <button key={ref} onClick={() => onOpen?.(ref)}>#{ref}</button>)}</span> : <span className="muted">无可引用证据</span>; }

export default function InvestigationPage({ params }: { params: { investigationId: string } }) {
  const router = useRouter();
  const [detail, setDetail] = useState<InvestigationDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [tab, setTab] = useState<'overview' | 'workflow' | 'evidence' | 'resolution'>('overview');
  const [selectedStage, setSelectedStage] = useState<InvestigationDetail['stages'][number]['name']>('source');
  const [selectedOperation, setSelectedOperation] = useState<string | null>(null);
  const [selectedEvidence, setSelectedEvidence] = useState<number | null>(null);
  const poll = useRef<ReturnType<typeof setTimeout> | null>(null);
  const load = useCallback(async () => { if (poll.current) clearTimeout(poll.current); try { const data = await fetchInvestigation(params.investigationId); setDetail(data); setError(null); if (data.status === 'queued' || data.status === 'running') poll.current = setTimeout(() => void load(), 3000); } catch (cause) { setError(String(cause)); } finally { setLoading(false); } }, [params.investigationId]);
  useEffect(() => { void load(); return () => { if (poll.current) clearTimeout(poll.current); }; }, [load]);
  useEffect(() => { if (!detail) return; const preferred = detail.stages.find((stage) => stage.status === 'running') || detail.stages.find((stage) => ['failed', 'partial', 'blocked'].includes(stage.status)) || detail.stages.find((stage) => stage.name === 'source'); if (preferred) setSelectedStage(preferred.name); }, [detail?.id]);
  const coverage = useMemo(() => detail ? Math.round((detail.stages.filter((stage) => stage.status === 'succeeded' || stage.status === 'partial').length / 7) * 100) : 0, [detail]);
  const activeStage = detail?.stages.find((stage) => stage.name === selectedStage) || null;
  const activeOperation = activeStage?.operations.find((operation) => operation.id === selectedOperation) || activeStage?.operations.find((operation) => operation.status === 'running') || activeStage?.operations.at(-1) || null;
  const activeEvidence = detail?.evidence.find((evidence) => evidence.id === selectedEvidence) || (activeOperation ? detail?.evidence.find((evidence) => activeOperation.artifact_refs.includes(evidence.id)) || null : null);
  const unknowns = detail?.stages.find((stage) => stage.name === 'reasoning')?.output.unknowns;
  const unknownList = Array.isArray(unknowns) ? unknowns.filter((item): item is string => typeof item === 'string') : [];
  const openEvidence = (id: number) => { setSelectedEvidence(id); setTab('evidence'); };
  async function restart() { if (!detail) return; setBusy(true); try { const next = await reinvestigate(detail.id); router.push(`/workbench/investigation/${next.id}`); } catch (cause) { setError(String(cause)); setBusy(false); } }
  async function copyPrompt() { if (detail?.remediation?.agent_prompt) await navigator.clipboard.writeText(detail.remediation.agent_prompt); }
  if (loading) return <div className="investigation-loading"><Workflow size={20} /> 正在加载调查...</div>;
  if (error || !detail) return <div className="investigation-loading investigation-error"><CircleAlert size={20} /> {error || '调查不存在'} <Button size="sm" variant="outline" onClick={() => void load()}>重试</Button></div>;
  const incidentVersion = detail.source_revisions.find((item) => item.role === 'incident'); const latestVersion = detail.source_revisions.find((item) => item.role === 'latest');
  return <main className="investigation-page">
    <header className="investigation-header"><div className="investigation-breadcrumb"><Link href="/workbench">调查</Link><ChevronRight size={14} /><span>{detail.application.name}</span><ChevronRight size={14} /><span className="mono">{detail.id.slice(0, 12)}</span></div><div className="investigation-header-row"><div className="investigation-title"><div className={`investigation-severity investigation-severity-${detail.alert?.level === 'CRITICAL' ? 'critical' : 'warning'}`}><CircleAlert size={18} /></div><div><h1>{detail.alert?.title || '未命名事故'}</h1><p>{detail.application.name} · {detail.scope.service || '未识别服务'} · {detail.scope.environment || '未识别环境'}</p></div></div><div className="investigation-actions"><Button size="sm" variant="outline" onClick={() => void load()} aria-label="刷新调查"><RefreshCw size={15} /></Button><Button size="sm" variant="primary" onClick={() => void restart()} disabled={busy}><Play size={14} />重新调查</Button></div></div><div className="investigation-meta"><Status status={detail.status}>{detail.status === 'completed' ? '已完成' : detail.status === 'needs_review' ? '待人工复核' : detail.status}</Status><span className="investigation-meta-item"><Clock3 size={14} />{time(detail.scope.window_started_at)} - {time(detail.scope.window_finished_at)}</span><span className="investigation-meta-item"><Clock3 size={14} />耗时 {duration(detail.started_at, detail.finished_at)}</span>{detail.scope.deployment_sha && <span className="investigation-meta-item mono"><GitCommitHorizontal size={14} />{detail.scope.deployment_sha.slice(0, 12)}</span>}</div></header>
    <nav className="investigation-tabs" aria-label="调查视图"><button aria-current={tab === 'overview' ? 'page' : undefined} onClick={() => setTab('overview')}>概览</button><button aria-current={tab === 'workflow' ? 'page' : undefined} onClick={() => setTab('workflow')}>执行流程</button><button aria-current={tab === 'evidence' ? 'page' : undefined} onClick={() => setTab('evidence')}>证据</button><button aria-current={tab === 'resolution' ? 'page' : undefined} onClick={() => setTab('resolution')}>根因与处置</button></nav>
    <div className="investigation-tab-panels">
      {tab === 'overview' && <section className="investigation-overview"><div className="investigation-conclusion"><div className="panel-kicker"><span>调查结论</span><Status status={detail.status}>{detail.status === 'needs_review' ? '待复核' : `置信度 ${detail.confidence === null ? '未生成' : `${Math.round(detail.confidence * 100)}%`}`}</Status></div><h2>{detail.conclusion || '正在等待可引用证据与归因结果。'}</h2><div className="investigation-conclusion-foot"><span>输出语言：{detail.output_language === 'zh' ? '中文' : 'English'}</span><span>调查 ID <code>{detail.id}</code></span></div></div><aside className="investigation-summary"><div><span>证据覆盖</span><strong>{coverage}%</strong><progress value={coverage} max="100" /></div><div><span>证据产物</span><strong>{detail.evidence.length}</strong></div><div><span>来源修订</span><strong>{detail.source_revisions.filter((row) => row.status === 'resolved').length}/2</strong></div><div><span>采集操作</span><strong>{detail.stages.reduce((sum, stage) => sum + stage.operations.length, 0)}</strong></div></aside><WorkflowMap stages={detail.stages} selected={selectedStage} onSelect={(stage) => { setSelectedStage(stage); setSelectedOperation(null); setTab('workflow'); }} /><section className="investigation-panel investigation-hypotheses"><div className="panel-heading"><div><p className="panel-kicker">ROOT CAUSE</p><h2>假设与关键未知项</h2></div><ShieldAlert size={18} /></div><div className="hypothesis-grid"><div>{detail.hypotheses.length ? detail.hypotheses.map((item) => <article key={item.rank} className="hypothesis-row"><span className={`hypothesis-rank hypothesis-${item.status}`}>{item.rank}</span><div><p>{item.text}</p><EvidenceRefs refs={item.evidence_refs} onOpen={openEvidence} /></div><strong>{Math.round(item.confidence * 100)}%</strong></article>) : <p className="muted">尚未生成根因假设。</p>}</div><div className="unknown-list"><p className="panel-kicker">仍待确认</p>{unknownList.length ? <ul>{unknownList.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">当前没有额外未知项。</p>}</div></div></section></section>}
      {tab === 'workflow' && <section className="workflow-workspace"><aside className="workflow-stage-rail" aria-label="调查阶段">{detail.stages.map((stage) => <button key={stage.name} aria-current={stage.name === selectedStage ? 'step' : undefined} onClick={() => { setSelectedStage(stage.name); setSelectedOperation(null); }}><span className={`workflow-rail-dot ${tone(stage.status)}`} /><span><strong>{STAGE_LABELS[stage.name]}</strong><small>{stage.operations.length} 个操作 · {duration(stage.started_at, stage.finished_at)}</small></span><Status status={stage.status}>{stageText(stage.status)}</Status></button>)}</aside><section className="workflow-operations"><div className="panel-heading"><div><p className="panel-kicker">EXECUTION TRACE</p><h2>{activeStage ? STAGE_LABELS[activeStage.name] : '执行过程'}</h2></div>{activeStage && <Status status={activeStage.status}>{stageText(activeStage.status)}</Status>}</div>{activeStage?.operations.length ? activeStage.operations.map((operation) => <button className={`workflow-operation ${operation.id === activeOperation?.id ? 'is-selected' : ''}`} key={operation.id} onClick={() => setSelectedOperation(operation.id)}><span className={`workflow-operation-dot ${tone(operation.status)}`} /><span className="workflow-operation-main"><strong>{OPERATION_LABELS[operation.type] || operation.type}</strong><small>{String(operation.detail.path || operation.detail.connector || operation.detail.requested_ref || operation.detail.reason || '已记录执行结果')}</small></span><span className="mono">{duration(operation.started_at, operation.finished_at)}</span><Status status={operation.status}>{operationText(operation.status)}</Status></button>) : <p className="workflow-empty">该阶段尚未产生操作事件。</p>}</section><aside className="workflow-inspector">{activeOperation ? <><div className="panel-heading"><div><p className="panel-kicker">OPERATION</p><h2>{OPERATION_LABELS[activeOperation.type] || activeOperation.type}</h2></div><Status status={activeOperation.status}>{operationText(activeOperation.status)}</Status></div><dl><div><dt>开始时间</dt><dd>{time(activeOperation.started_at)}</dd></div><div><dt>耗时</dt><dd>{duration(activeOperation.started_at, activeOperation.finished_at)}</dd></div>{Object.entries(activeOperation.detail).filter(([, value]) => typeof value !== 'object').map(([key, value]) => <div key={key}><dt>{key}</dt><dd className="mono">{String(value)}</dd></div>)}</dl><div className="workflow-inspector-evidence"><span>关联证据</span><EvidenceRefs refs={activeOperation.artifact_refs} onOpen={openEvidence} /></div><InvestigationCodeViewer evidence={activeEvidence} /></> : <p className="muted">选择一个操作以查看可审计的输入、输出和证据。</p>}</aside></section>}
      {tab === 'evidence' && <section className="investigation-evidence"><div className="panel-heading"><div><p className="panel-kicker">IMMUTABLE EVIDENCE</p><h2>证据清单</h2></div><span className="muted">{detail.evidence.length} 项已脱敏产物</span></div><div className="source-revisions"><div><FileCode2 size={16} /><span>事故版本</span><code>{incidentVersion?.resolved_sha || incidentVersion?.requested_ref || '未解析'}</code><Status status={incidentVersion?.status || 'not_configured'}>{incidentVersion?.status || '未配置'}</Status></div><div><GitCommitHorizontal size={16} /><span>当前分支</span><code>{latestVersion?.resolved_sha || latestVersion?.requested_ref || '未解析'}</code><Status status={latestVersion?.status || 'not_configured'}>{latestVersion?.status || '未配置'}</Status></div></div><div className="evidence-table" role="table"><div className="evidence-table-head" role="row"><span>来源</span><span>类型与定位</span><span>关联键</span><span>采集时间</span></div>{detail.evidence.map((item) => <button role="row" className={selectedEvidence === item.id ? 'is-selected' : ''} key={item.id} onClick={() => setSelectedEvidence(item.id)}><span className="evidence-source"><Database size={15} />{SOURCE_LABELS[item.source] || item.source}</span><span><strong>{item.type}</strong><code>{item.locator || '无定位符'}</code><p>{item.excerpt}</p></span><span className="mono">#{item.id}</span><time>{time(item.collected_at)}</time></button>)}</div><InvestigationCodeViewer evidence={activeEvidence} /></section>}
      {tab === 'resolution' && <section className="investigation-resolution"><div className="panel-heading"><div><p className="panel-kicker">REMEDIATION</p><h2>风险受控的处置方案</h2></div>{detail.remediation && <Status status={detail.remediation.risk_level === 'low' ? 'succeeded' : 'blocked'}>{detail.remediation.risk_level} 风险</Status>}</div>{detail.remediation ? <><p className="resolution-summary">{detail.remediation.summary}</p><EvidenceRefs refs={detail.remediation.evidence_refs} onOpen={openEvidence} /><div className="resolution-grid"><Detail title="前置条件" items={detail.remediation.preconditions} /><section><h3>建议步骤</h3><ol>{detail.remediation.steps.map((step, index) => <li key={index}><strong>{step.action || '人工处置步骤'}</strong>{step.expected_result && <span>{step.expected_result}</span>}</li>)}</ol></section><Detail title="人工验证" items={detail.remediation.verification} /><Detail title="回滚方案" items={detail.remediation.rollback} /></div><div className="agent-prompt"><div><ListTree size={16} /><span>外部 Agent 调查提示</span></div><Button size="sm" variant="outline" onClick={() => void copyPrompt()}><Copy size={14} />复制</Button><pre>{detail.remediation.agent_prompt}</pre></div></> : <p className="muted">处置方案将在归因阶段完成后生成。</p>}</section>}
    </div>
  </main>;
}

function WorkflowMap({ stages, selected, onSelect }: { stages: InvestigationDetail['stages']; selected: string; onSelect: (stage: InvestigationDetail['stages'][number]['name']) => void }) { return <section className="investigation-flow-map" aria-label="调查执行流程"><div className="panel-heading"><div><p className="panel-kicker">INVESTIGATION FLOW</p><h2>调查执行流程</h2></div><span className="muted">全部状态来自持久化阶段与操作事件</span></div><div className="flow-map-track">{stages.map((stage, index) => <button key={stage.name} className={stage.name === selected ? 'is-selected' : ''} aria-pressed={stage.name === selected} onClick={() => onSelect(stage.name)}><span className={`flow-map-index ${tone(stage.status)}`}>{index + 1}</span><strong>{STAGE_LABELS[stage.name]}</strong><small>{stage.operations.length} 操作 · {stage.collections.reduce((sum, item) => sum + item.artifact_count, 0)} 产物</small><Status status={stage.status}>{stageText(stage.status)}</Status></button>)}</div></section>; }
function Detail({ title, items }: { title: string; items: string[] }) { return <section><h3>{title}</h3>{items.length ? <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="muted">未提供</p>}</section>; }
