"""Declarative base and shared metadata.

A single naming convention is declared so that every constraint/index
generated by SQLAlchemy or Alembic follows a predictable, reviewable pattern.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    # PostgreSQL's default search path is the deployment contract. Keeping the
    # Unqualified metadata matches the explicit current DDL and makes Alembic drift
    # detection compare the same table identities.
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
