"""Frozen V1 schema for sequential, evidence-backed investigations.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-25

This is intentionally the only database baseline. V1 deployments start from a
new database and do not transform historical execution payloads.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_ref', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('openai', 'anthropic')", name=op.f('ck_ai_model_configs_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_model_configs'))
    )
    op.create_index('ux_ai_model_configs_default', 'ai_model_configs', ['is_default'], unique=True, postgresql_where='is_default')
    op.create_table('git_credentials',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('auth_type', sa.Text(), server_default='ssh', nullable=False),
    sa.Column('username', sa.Text(), server_default='', nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('readonly', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_type IN ('ssh', 'https')", name=op.f('ck_git_credentials_auth_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_credentials'))
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key <> 'ai_output_language' OR value IN ('en', 'zh')", name=op.f('ck_platform_settings_ai_output_language')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='user', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user')", name=op.f('ck_users_role')),
    sa.CheckConstraint("status IN ('pending', 'active', 'disabled')", name=op.f('ck_users_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('model_config_id', sa.BigInteger(), nullable=True),
    sa.Column('ingestion_state', sa.Text(), server_default='draft', nullable=False),
    sa.Column('ingestion_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingestion_start_position', sa.Text(), nullable=True),
    sa.Column('ingestion_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ingestion_start_position IS NULL OR ingestion_start_position IN ('earliest', 'latest')", name=op.f('ck_applications_ingestion_start_position')),
    sa.CheckConstraint("ingestion_state IN ('draft', 'active', 'paused')", name=op.f('ck_applications_ingestion_state')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_applications_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_config_id'], ['ai_model_configs.id'], name=op.f('fk_applications_model_config_id_ai_model_configs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_table('invites',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'revoked')", name=op.f('ck_invites_status')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invites_invited_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_invites_token'))
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('alert_id', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('CRITICAL', 'WARNING')", name=op.f('ck_alerts_level')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_alerts_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_application_id', 'alerts', ['application_id'], unique=False)
    op.create_index('ix_alerts_dedupe_key', 'alerts', ['dedupe_key'], unique=False)
    op.create_index('ix_alerts_fields', 'alerts', ['fields'], unique=False, postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.create_table('application_descriptions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('description_type', sa.Text(), server_default='deploy', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("description_type IN ('deploy', 'other')", name=op.f('ck_application_descriptions_description_type')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_descriptions_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_descriptions'))
    )
    op.create_table('application_ingestion_offsets',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_version', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('start_position', sa.Text(), nullable=False),
    sa.Column('target_offset', sa.BigInteger(), nullable=False),
    sa.Column('initialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("start_position IN ('earliest', 'latest')", name=op.f('ck_application_ingestion_offsets_start_position')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_ingestion_offsets_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'ingestion_version', 'topic', 'partition', name=op.f('pk_application_ingestion_offsets'))
    )
    op.create_index('ix_application_ingestion_offsets_topic', 'application_ingestion_offsets', ['topic', 'partition'], unique=False)
    op.create_table('application_ingestion_runtime',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_state', sa.Text(), server_default='idle', nullable=False),
    sa.Column('observed_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumer_id', sa.Text(), nullable=True),
    sa.Column('assigned_partitions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('backlog', sa.BigInteger(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("observed_state IN ('idle', 'starting', 'listening', 'paused', 'error')", name=op.f('ck_application_ingestion_runtime_observed_state')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_ingestion_runtime_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', name=op.f('pk_application_ingestion_runtime'))
    )
    op.create_table('application_integrations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='active', nullable=False),
    sa.Column('readonly_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('redis', 'kafka', 'clickhouse')", name=op.f('ck_application_integrations_kind')),
    sa.CheckConstraint("state IN ('active', 'disabled')", name=op.f('ck_application_integrations_state')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_integrations_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_integrations'))
    )
    op.create_index('ix_application_integrations_application_id', 'application_integrations', ['application_id'], unique=False)
    op.create_table('application_kafka',
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_kafka_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', name=op.f('pk_application_kafka')),
    sa.UniqueConstraint('topic', name=op.f('uq_application_kafka_topic'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_email', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), server_default='ok', nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_audit_events_application_id_applications'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_id', 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_table('db_sources',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('conn_secret_ref', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('sslmode', sa.Text(), nullable=True),
    sa.Column('allowed_tables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sensitive_columns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(conn_secret_ref IS NOT NULL AND conn_secret_ref ~ '^env://[A-Za-z_][A-Za-z0-9_]*$' AND host IS NULL AND port IS NULL AND database IS NULL AND username IS NULL AND password IS NULL AND sslmode IS NULL) OR (conn_secret_ref IS NULL AND host IS NOT NULL AND database IS NOT NULL AND sslmode = 'verify-full')", name=op.f('ck_db_sources_secure_connection')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_db_sources_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_db_sources'))
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('offset', sa.BigInteger(), nullable=True),
    sa.Column('replayed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_dead_letters_application_id_applications'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letters'))
    )
    op.create_index('ix_dead_letters_created_at', 'dead_letters', ['created_at'], unique=False)
    op.create_index('ix_dead_letters_kind', 'dead_letters', ['kind'], unique=False)
    op.create_index('uq_dead_letters_source', 'dead_letters', ['topic', 'partition', 'offset', 'kind'], unique=True, postgresql_where=sa.text('partition IS NOT NULL AND "offset" IS NOT NULL'))
    op.create_table('evidence_connectors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='active', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('diagnostic_profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('collection_budget_seconds', sa.Integer(), server_default='15', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('loki', 'prometheus', 'tempo', 'postgres', 'redis', 'kafka', 'clickhouse')", name=op.f('ck_evidence_connectors_kind')),
    sa.CheckConstraint("state IN ('active', 'disabled')", name=op.f('ck_evidence_connectors_state')),
    sa.CheckConstraint('collection_budget_seconds BETWEEN 1 AND 60', name=op.f('ck_evidence_connectors_budget')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_evidence_connectors_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_connectors'))
    )
    op.create_index('ix_evidence_connectors_application', 'evidence_connectors', ['application_id', 'state'], unique=False)
    op.create_table('git_repos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.Text(), server_default='main', nullable=False),
    sa.Column('scope', sa.Text(), server_default='global', nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('repo_type', sa.Text(), server_default='other', nullable=False),
    sa.Column('credential_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'global' AND application_id IS NULL) OR (scope = 'application' AND application_id IS NOT NULL)", name=op.f('ck_git_repos_scope_application')),
    sa.CheckConstraint("scope IN ('global', 'application')", name=op.f('ck_git_repos_scope')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_git_repos_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credential_id'], ['git_credentials.id'], name=op.f('fk_git_repos_credential_id_git_credentials'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_repos'))
    )
    op.create_index('ux_git_repos_app_repo_url', 'git_repos', ['application_id', 'repo_url'], unique=True, postgresql_where="scope = 'application'")
    op.create_index('ux_git_repos_global_repo_url', 'git_repos', ['repo_url'], unique=True, postgresql_where="scope = 'global'")
    op.create_table('ingestion_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('offset', sa.BigInteger(), nullable=True),
    sa.Column('producer_event_id', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='accepted', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('accepted', 'dlq', 'unassigned')", name=op.f('ck_ingestion_events_status')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_ingestion_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_events'))
    )
    op.create_index('uq_ingestion_events_topic_partition_offset', 'ingestion_events', ['topic', 'partition', 'offset'], unique=True)
    op.create_table('user_application_perms',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('perm', sa.Text(), server_default='read', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("perm IN ('read', 'analyze', 'admin')", name=op.f('ck_user_application_perms_perm')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_user_application_perms_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_application_perms_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'application_id', name=op.f('pk_user_application_perms'))
    )
    op.create_table('application_repos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_repos_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repos.id'], name=op.f('fk_application_repos_repo_id_git_repos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_repos')),
    sa.UniqueConstraint('application_id', 'repo_id', name='uq_app_repo')
    )
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='open', nullable=False),
    sa.Column('first_alert_id', sa.BigInteger(), nullable=True),
    sa.Column('latest_alert_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('open', 'resolved', 'suppressed')", name=op.f('ck_incidents_state')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_incidents_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_alert_id'], ['alerts.id'], name=op.f('fk_incidents_first_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latest_alert_id'], ['alerts.id'], name=op.f('fk_incidents_latest_alert_id_alerts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('public_id', name=op.f('uq_incidents_public_id'))
    )
    op.create_index('uq_incidents_application_id_dedupe_key', 'incidents', ['application_id', 'dedupe_key'], unique=True)
    op.create_table('investigations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_signature', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('result_state', sa.Text(), server_default='pending', nullable=False),
    sa.Column('output_language', sa.Text(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('deployment_sha', sa.Text(), nullable=True),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('review_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('review_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('audit_status', sa.Text(), server_default='auditable', nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=True),
    sa.Column('report_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('event_cursor', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audit_status IN ('auditable', 'unverifiable', 'violated')", name=op.f('ck_investigations_audit_status')),
    sa.CheckConstraint("output_language IN ('en', 'zh')", name=op.f('ck_investigations_output_language')),
    sa.CheckConstraint("result_state IN ('pending', 'confirmed', 'hypothesis', 'insufficient', 'unavailable')", name=op.f('ck_investigations_result_state')),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name=op.f('ck_investigations_status')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_investigations_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_investigations_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_investigations_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations')),
    sa.UniqueConstraint('public_id', name=op.f('uq_investigations_public_id'))
    )
    op.create_index('ix_investigations_application_created', 'investigations', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_investigations_incident', 'investigations', ['incident_id'], unique=False)
    op.create_table('investigation_findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), server_default='', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('fact', 'hypothesis', 'counter_evidence', 'impact', 'evidence_gap', 'conclusion')", name=op.f('ck_investigation_findings_kind')),
    sa.CheckConstraint("status IN ('supported', 'leading', 'contradicted', 'required', 'confirmed')", name=op.f('ck_investigation_findings_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_findings_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_findings'))
    )
    op.create_index('uq_investigation_findings_ordinal', 'investigation_findings', ['investigation_id', 'ordinal'], unique=True)
    op.create_table('investigation_inputs',
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_name', sa.Text(), server_default='Error', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('error_cause', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'WARNING')", name=op.f('ck_investigation_inputs_severity')),
    sa.CheckConstraint("source_type IN ('kafka', 'manual')", name=op.f('ck_investigation_inputs_source_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_investigation_inputs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_inputs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_investigation_inputs'))
    )
    op.create_table('investigation_jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.Text(), nullable=True),
    sa.Column('last_error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'retry_wait', 'succeeded', 'dead')", name=op.f('ck_investigation_jobs_status')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_investigation_jobs_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_jobs_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_jobs')),
    sa.UniqueConstraint('public_id', name=op.f('uq_investigation_jobs_public_id'))
    )
    op.create_index('ix_investigation_jobs_available', 'investigation_jobs', ['status', 'available_at', 'priority', 'created_at'], unique=False)
    op.create_index('uq_investigation_jobs_active_incident', 'investigation_jobs', ['incident_id'], unique=True, postgresql_where=sa.text("incident_id IS NOT NULL AND status IN ('queued', 'running', 'retry_wait')"))
    op.create_table('investigation_reports',
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('result_state', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('incident_cause', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('code_diagnosis', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confirmed_facts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('counter_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('evidence_gaps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('next_step', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('schema_version', sa.Text(), server_default='investigation-report.v1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result_state IN ('confirmed', 'hypothesis', 'insufficient', 'unavailable')", name=op.f('ck_investigation_reports_result_state')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_reports_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', name=op.f('pk_investigation_reports'))
    )
    op.create_table('investigation_steps',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('expected_evidence', sa.Text(), server_default='', nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('input_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('output_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('result_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('intake', 'triage', 'source', 'observability', 'dependency', 'evidence_request', 'synthesis')", name=op.f('ck_investigation_steps_kind')),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'partial', 'blocked', 'failed', 'canceled')", name=op.f('ck_investigation_steps_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_steps_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_steps')),
    sa.UniqueConstraint('public_id', name=op.f('uq_investigation_steps_public_id'))
    )
    op.create_index('uq_investigation_steps_ordinal', 'investigation_steps', ['investigation_id', 'ordinal'], unique=True)
    op.create_index('uq_investigation_steps_running', 'investigation_steps', ['investigation_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_table('source_revisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('requested_ref', sa.Text(), nullable=True),
    sa.Column('resolved_sha', sa.Text(), nullable=True),
    sa.Column('resolution_basis', sa.Text(), nullable=True),
    sa.Column('origin_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('incident', 'latest')", name=op.f('ck_source_revisions_role')),
    sa.CheckConstraint("status IN ('queued', 'resolved', 'unresolved', 'failed')", name=op.f('ck_source_revisions_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_source_revisions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repos.id'], name=op.f('fk_source_revisions_repo_id_git_repos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_revisions'))
    )
    op.create_index('uq_source_revisions_run_repo_role', 'source_revisions', ['investigation_id', 'repo_id', 'role'], unique=True)
    op.create_table('evidence_collections',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('connector_kind', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('selector', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config_hash', sa.Text(), nullable=True),
    sa.Column('collector_version', sa.Text(), server_default='1', nullable=False),
    sa.Column('artifact_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'partial', 'blocked', 'failed')", name=op.f('ck_evidence_collections_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_collections_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['investigation_steps.id'], name=op.f('fk_evidence_collections_step_id_investigation_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_collections'))
    )
    op.create_index('ix_evidence_collections_investigation', 'evidence_collections', ['investigation_id', 'step_id'], unique=False)
    op.create_table('investigation_ai_invocations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('prompt_template_version', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('output_hash', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_source', sa.Text(), server_default='unavailable', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('succeeded', 'failed', 'unavailable')", name=op.f('ck_investigation_ai_invocations_status')),
    sa.CheckConstraint("token_source IN ('provider', 'estimated', 'unavailable')", name=op.f('ck_investigation_ai_invocations_token_source')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_ai_invocations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['investigation_steps.id'], name=op.f('fk_investigation_ai_invocations_step_id_investigation_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_ai_invocations'))
    )
    op.create_index('ix_investigation_ai_invocations_run', 'investigation_ai_invocations', ['investigation_id', 'step_id', 'created_at'], unique=False)
    op.create_table('investigation_decisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('after_step_id', sa.BigInteger(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('selected_tool', sa.Text(), nullable=True),
    sa.Column('action_fingerprint', sa.Text(), nullable=True),
    sa.Column('rationale_summary', sa.Text(), nullable=False),
    sa.Column('hypothesis_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('execute', 'stop_confirmed', 'stop_hypothesis', 'stop_insufficient', 'stop_unavailable')", name=op.f('ck_investigation_decisions_action')),
    sa.ForeignKeyConstraint(['after_step_id'], ['investigation_steps.id'], name=op.f('fk_investigation_decisions_after_step_id_investigation_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_decisions_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_decisions'))
    )
    op.create_index('uq_investigation_decisions_fingerprint', 'investigation_decisions', ['investigation_id', 'action_fingerprint'], unique=True, postgresql_where=sa.text('action_fingerprint IS NOT NULL'))
    op.create_index('uq_investigation_decisions_ordinal', 'investigation_decisions', ['investigation_id', 'ordinal'], unique=True)
    op.create_table('investigation_finding_edges',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('from_finding_id', sa.BigInteger(), nullable=False),
    sa.Column('to_finding_id', sa.BigInteger(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.CheckConstraint("relation IN ('supports', 'contradicts', 'caused_by', 'needs_test')", name=op.f('ck_investigation_finding_edges_relation')),
    sa.ForeignKeyConstraint(['from_finding_id'], ['investigation_findings.id'], name=op.f('fk_investigation_finding_edges_from_finding_id_investigation_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_finding_edges_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_finding_id'], ['investigation_findings.id'], name=op.f('fk_investigation_finding_edges_to_finding_id_investigation_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_finding_edges'))
    )
    op.create_index('ix_investigation_finding_edges_run', 'investigation_finding_edges', ['investigation_id', 'from_finding_id', 'to_finding_id'], unique=False)
    op.create_table('investigation_operations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('result_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor IN ('engine', 'ai', 'collector')", name=op.f('ck_investigation_operations_actor')),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'partial', 'blocked', 'failed', 'canceled')", name=op.f('ck_investigation_operations_status')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_operations_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['investigation_steps.id'], name=op.f('fk_investigation_operations_step_id_investigation_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_operations')),
    sa.UniqueConstraint('public_id', name=op.f('uq_investigation_operations_public_id'))
    )
    op.create_index('ix_investigation_operations_step', 'investigation_operations', ['step_id', 'ordinal'], unique=False)
    op.create_index('uq_investigation_operations_ordinal', 'investigation_operations', ['investigation_id', 'ordinal'], unique=True)
    op.create_index('uq_investigation_operations_running', 'investigation_operations', ['investigation_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('redacted_excerpt', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('incident_input', 'source_file', 'source_diff', 'log', 'metric', 'trace', 'dependency', 'database', 'operator_input')", name=op.f('ck_evidence_artifacts_type')),
    sa.ForeignKeyConstraint(['collection_id'], ['evidence_collections.id'], name=op.f('fk_evidence_artifacts_collection_id_evidence_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_artifacts_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts'))
    )
    op.create_index('ix_evidence_artifacts_investigation', 'evidence_artifacts', ['investigation_id', 'collection_id'], unique=False)
    op.create_table('investigation_operation_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('started', 'progress', 'finished')", name=op.f('ck_investigation_operation_events_kind')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_operation_events_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['investigation_operations.id'], name=op.f('fk_investigation_operation_events_operation_id_investigation_operations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['investigation_steps.id'], name=op.f('fk_investigation_operation_events_step_id_investigation_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_operation_events'))
    )
    op.create_index('ix_investigation_operation_events_operation', 'investigation_operation_events', ['operation_id', 'sequence'], unique=False)
    op.create_index('uq_investigation_operation_events_sequence', 'investigation_operation_events', ['investigation_id', 'sequence'], unique=True)
    op.create_table('investigation_code_findings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=True),
    sa.Column('revision', sa.Text(), nullable=True),
    sa.Column('revision_role', sa.Text(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Text(), nullable=True),
    sa.Column('faulty_behavior', sa.Text(), nullable=False),
    sa.Column('why_wrong', sa.Text(), nullable=False),
    sa.Column('expected_behavior', sa.Text(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('incident_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('supporting_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('counter_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('missing_validation', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('fix_direction', sa.Text(), server_default='', nullable=False),
    sa.Column('test_scenario', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("revision_role IS NULL OR revision_role IN ('incident', 'latest')", name=op.f('ck_investigation_code_findings_revision_role')),
    sa.CheckConstraint("status IN ('confirmed', 'hypothesis', 'no_defect', 'not_found')", name=op.f('ck_investigation_code_findings_status')),
    sa.CheckConstraint('end_line IS NULL OR end_line >= start_line', name=op.f('ck_investigation_code_findings_end_line')),
    sa.CheckConstraint('start_line IS NULL OR start_line > 0', name=op.f('ck_investigation_code_findings_start_line')),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], name=op.f('fk_investigation_code_findings_artifact_id_evidence_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_code_findings_investigation_id_investigations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['git_repos.id'], name=op.f('fk_investigation_code_findings_repo_id_git_repos'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_code_findings'))
    )
    op.create_index('ix_investigation_code_findings_run', 'investigation_code_findings', ['investigation_id', 'status'], unique=False)
    op.create_table('investigation_evidence_links',
    sa.Column('investigation_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation IN ('collected', 'manual')", name=op.f('ck_investigation_evidence_links_relation')),
    sa.ForeignKeyConstraint(['artifact_id'], ['evidence_artifacts.id'], name=op.f('fk_investigation_evidence_links_artifact_id_evidence_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_evidence_links_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('investigation_id', 'artifact_id', name=op.f('pk_investigation_evidence_links'))
    )
    op.create_index('ix_investigation_evidence_links_artifact', 'investigation_evidence_links', ['artifact_id'], unique=False)
    op.execute(sa.text("""
        CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """))
    op.execute(sa.text("""
        DO $$
        DECLARE table_name text;
        BEGIN
            FOREACH table_name IN ARRAY ARRAY[
                'ai_model_configs', 'applications', 'application_kafka',
                'application_ingestion_runtime', 'application_repos',
                'application_descriptions', 'db_sources', 'git_credentials',
                'git_repos', 'incidents', 'dead_letters',
                'application_integrations', 'investigations',
                'evidence_connectors', 'user_application_perms',
                'platform_settings', 'users', 'invites'
            ] LOOP
                EXECUTE format(
                    'CREATE TRIGGER trg_%1$s_updated_at BEFORE UPDATE ON %1$I '
                    'FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
                    table_name
                );
            END LOOP;
        END $$
    """))
    op.execute(sa.text("""
        CREATE FUNCTION reject_evidence_artifact_update() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'evidence artifacts are immutable';
        END;
        $$ LANGUAGE plpgsql
    """))
    op.execute(sa.text("""
        CREATE TRIGGER trg_evidence_artifacts_immutable
        BEFORE UPDATE ON evidence_artifacts
        FOR EACH ROW EXECUTE FUNCTION reject_evidence_artifact_update()
    """))
    op.execute(sa.text("""
        CREATE FUNCTION reject_secret_bearing_config() RETURNS trigger AS $$
        BEGIN
            IF jsonb_path_exists(NEW.config, '$.**.password')
               OR jsonb_path_exists(NEW.config, '$.**.passwd')
               OR jsonb_path_exists(NEW.config, '$.**.secret')
               OR jsonb_path_exists(NEW.config, '$.**.token')
               OR jsonb_path_exists(NEW.config, '$.**.api_key')
               OR jsonb_path_exists(NEW.config, '$.**.access_key') THEN
                RAISE EXCEPTION 'connector config may not contain credentials';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
    """))
    for table_name in ("application_integrations", "evidence_connectors"):
        op.execute(sa.text(f"""
            CREATE TRIGGER trg_{table_name}_secret_free_config
            BEFORE INSERT OR UPDATE OF config ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION reject_secret_bearing_config()
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_secret_bearing_config() CASCADE"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS reject_evidence_artifact_update() CASCADE"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS set_updated_at() CASCADE"))
    op.drop_index('ix_investigation_evidence_links_artifact', table_name='investigation_evidence_links')
    op.drop_table('investigation_evidence_links')
    op.drop_index('ix_investigation_code_findings_run', table_name='investigation_code_findings')
    op.drop_table('investigation_code_findings')
    op.drop_index('uq_investigation_operation_events_sequence', table_name='investigation_operation_events')
    op.drop_index('ix_investigation_operation_events_operation', table_name='investigation_operation_events')
    op.drop_table('investigation_operation_events')
    op.drop_index('ix_evidence_artifacts_investigation', table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index('uq_investigation_operations_running', table_name='investigation_operations', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('uq_investigation_operations_ordinal', table_name='investigation_operations')
    op.drop_index('ix_investigation_operations_step', table_name='investigation_operations')
    op.drop_table('investigation_operations')
    op.drop_index('ix_investigation_finding_edges_run', table_name='investigation_finding_edges')
    op.drop_table('investigation_finding_edges')
    op.drop_index('uq_investigation_decisions_ordinal', table_name='investigation_decisions')
    op.drop_index('uq_investigation_decisions_fingerprint', table_name='investigation_decisions', postgresql_where=sa.text('action_fingerprint IS NOT NULL'))
    op.drop_table('investigation_decisions')
    op.drop_index('ix_investigation_ai_invocations_run', table_name='investigation_ai_invocations')
    op.drop_table('investigation_ai_invocations')
    op.drop_index('ix_evidence_collections_investigation', table_name='evidence_collections')
    op.drop_table('evidence_collections')
    op.drop_index('uq_source_revisions_run_repo_role', table_name='source_revisions')
    op.drop_table('source_revisions')
    op.drop_index('uq_investigation_steps_running', table_name='investigation_steps', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('uq_investigation_steps_ordinal', table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_table('investigation_reports')
    op.drop_index('uq_investigation_jobs_active_incident', table_name='investigation_jobs', postgresql_where=sa.text("incident_id IS NOT NULL AND status IN ('queued', 'running', 'retry_wait')"))
    op.drop_index('ix_investigation_jobs_available', table_name='investigation_jobs')
    op.drop_table('investigation_jobs')
    op.drop_table('investigation_inputs')
    op.drop_index('uq_investigation_findings_ordinal', table_name='investigation_findings')
    op.drop_table('investigation_findings')
    op.drop_index('ix_investigations_incident', table_name='investigations')
    op.drop_index('ix_investigations_application_created', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('uq_incidents_application_id_dedupe_key', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('application_repos')
    op.drop_table('user_application_perms')
    op.drop_index('uq_ingestion_events_topic_partition_offset', table_name='ingestion_events')
    op.drop_table('ingestion_events')
    op.drop_index('ux_git_repos_global_repo_url', table_name='git_repos', postgresql_where="scope = 'global'")
    op.drop_index('ux_git_repos_app_repo_url', table_name='git_repos', postgresql_where="scope = 'application'")
    op.drop_table('git_repos')
    op.drop_index('ix_evidence_connectors_application', table_name='evidence_connectors')
    op.drop_table('evidence_connectors')
    op.drop_index('uq_dead_letters_source', table_name='dead_letters', postgresql_where=sa.text('partition IS NOT NULL AND "offset" IS NOT NULL'))
    op.drop_index('ix_dead_letters_kind', table_name='dead_letters')
    op.drop_index('ix_dead_letters_created_at', table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_table('db_sources')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('application_kafka')
    op.drop_index('ix_application_integrations_application_id', table_name='application_integrations')
    op.drop_table('application_integrations')
    op.drop_table('application_ingestion_runtime')
    op.drop_index('ix_application_ingestion_offsets_topic', table_name='application_ingestion_offsets')
    op.drop_table('application_ingestion_offsets')
    op.drop_table('application_descriptions')
    op.drop_index('ix_alerts_fields', table_name='alerts', postgresql_using='gin', postgresql_ops={'fields': 'jsonb_path_ops'})
    op.drop_index('ix_alerts_dedupe_key', table_name='alerts')
    op.drop_index('ix_alerts_application_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('invites')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_table('platform_settings')
    op.drop_table('git_credentials')
    op.drop_index('ux_ai_model_configs_default', table_name='ai_model_configs', postgresql_where='is_default')
    op.drop_table('ai_model_configs')
    # ### end Alembic commands ###
