"""Final ORM registry.

Only final-schema models are imported here. Deprecated identity,
single-model configuration, and product-specific integration tables must never
be registered alongside this metadata.
"""

from lode.db.models.connectors import EvidenceAccessScope, EvidenceConnector
from lode.db.models.evidence_access_audit import (
    AuthorizedEvidenceRead,
    EvidenceAccessDecision,
    EvidenceReadAttempt,
    NativeReadCandidate,
    SealedEvidenceValue,
)
from lode.db.models.evidence_graph import (
    EvidenceArtifact,
    EvidenceAssertion,
    EvidenceCollection,
    EvidenceLink,
    ObservedEntity,
    ObservedEvent,
    ObservedRelation,
)
from lode.db.models.intake import Alert, DeadLetter, Incident, IngestionEvent, InvestigationJob
from lode.db.models.investigation import (
    ContextBundleRevision,
    ContextSummaryArtifact,
    Investigation,
    InvestigationBuildUnitSnapshot,
    InvestigationComponentSnapshot,
    InvestigationConnectorSnapshot,
    InvestigationDecision,
    InvestigationDescriptorSnapshot,
    InvestigationInput,
    InvestigationModelBindingSnapshot,
    InvestigationModelPolicySnapshot,
    InvestigationOperation,
    InvestigationOperationEvent,
    InvestigationRepositorySnapshot,
    InvestigationResourceGraphSnapshot,
    InvestigationStep,
    ModelRoutingDecision,
)
from lode.db.models.model_portfolio import (
    AIProviderAccount,
    ContextPolicyRevision,
    ProviderAccountModel,
    ModelPolicyRevision,
    WorkspaceModelBinding,
)
from lode.db.models.resources import (
    BuildUnit,
    Component,
    ComponentDescriptor,
    ComponentSourceBinding,
    GitAccount,
    GitAccountCredentialRevision,
    GitAccountRepositoryAccess,
    GitAccountSyncJob,
    GitRepository,
    IdentityResolution,
    RepositoryDescriptor,
    ResourceGraphRevision,
    ResourceGraphRevisionMember,
    ResourceObservation,
    SemanticAnnotation,
    WorkspaceGitAccountGrant,
    WorkspaceGitRepositoryEntitlement,
    WorkspaceRepositoryBinding,
)
from lode.db.models.source_report import (
    AIInvocation,
    InvestigationCodeFinding,
    InvestigationReport,
    SourceAssessment,
    SourceRevision,
)
from lode.db.models.user import User
from lode.db.models.workspace import (
    AuditEvent,
    InvestigationPolicyRevision,
    PlatformSettings,
    Workspace,
    WorkspaceIngestionOffset,
    WorkspaceIngestionRuntime,
    WorkspacePermission,
)

__all__ = [
    "AIProviderAccount",
    "AIInvocation",
    "Alert",
    "AuditEvent",
    "AuthorizedEvidenceRead",
    "BuildUnit",
    "Component",
    "ComponentDescriptor",
    "ComponentSourceBinding",
    "ContextBundleRevision",
    "ContextPolicyRevision",
    "ContextSummaryArtifact",
    "DeadLetter",
    "EvidenceAccessScope",
    "EvidenceAccessDecision",
    "EvidenceArtifact",
    "EvidenceAssertion",
    "EvidenceCollection",
    "EvidenceConnector",
    "EvidenceLink",
    "EvidenceReadAttempt",
    "GitAccount",
    "GitAccountCredentialRevision",
    "GitAccountRepositoryAccess",
    "GitAccountSyncJob",
    "GitRepository",
    "IdentityResolution",
    "Incident",
    "IngestionEvent",
    "InvestigationJob",
    "Investigation",
    "InvestigationBuildUnitSnapshot",
    "InvestigationCodeFinding",
    "InvestigationComponentSnapshot",
    "InvestigationConnectorSnapshot",
    "InvestigationDecision",
    "InvestigationDescriptorSnapshot",
    "InvestigationInput",
    "InvestigationModelBindingSnapshot",
    "InvestigationModelPolicySnapshot",
    "InvestigationOperation",
    "InvestigationOperationEvent",
    "InvestigationReport",
    "InvestigationRepositorySnapshot",
    "InvestigationResourceGraphSnapshot",
    "InvestigationStep",
    "InvestigationPolicyRevision",
    "ProviderAccountModel",
    "ModelPolicyRevision",
    "ModelRoutingDecision",
    "PlatformSettings",
    "NativeReadCandidate",
    "ObservedEntity",
    "ObservedEvent",
    "ObservedRelation",
    "RepositoryDescriptor",
    "ResourceGraphRevision",
    "ResourceGraphRevisionMember",
    "ResourceObservation",
    "SemanticAnnotation",
    "SealedEvidenceValue",
    "SourceAssessment",
    "SourceRevision",
    "User",
    "Workspace",
    "WorkspaceIngestionOffset",
    "WorkspaceIngestionRuntime",
    "WorkspaceModelBinding",
    "WorkspaceGitAccountGrant",
    "WorkspaceGitRepositoryEntitlement",
    "WorkspacePermission",
    "WorkspaceRepositoryBinding",
]
