// Geist icons, re-exported from the official @geist-ui/icons package so the rest
// of the app can keep importing them as `Icon*` (no per-file imports). These are
// Vercel's Geist icon set (stroke=currentColor, 1.5 stroke, 24x24 viewBox).
export {
  Home as IconHome,
  BarChart as IconBarChart,
  Database as IconDatabase,
  Settings as IconSettings,
  Users as IconUsers,
  Search as IconSearch,
  Globe as IconGlobe,
  Sun as IconSun,
  Moon as IconMoon,
  LogOut as IconLogOut,
  Check as IconCheck,
  X as IconX,
  ChevronDown as IconChevronDown,
  Plus as IconPlus,
  ExternalLink as IconExternalLink,
  Copy as IconCopy,
  Trash as IconTrash2,
  Edit as IconEdit2,
  Info as IconInfo,
  AlertTriangle as IconAlertTriangle,
  RefreshCw as IconRefreshCw,
  MoreVertical as IconMoreVertical,
  ArrowUpRight as IconArrowUpRight,
  Link as IconLink,
  Mail as IconMail,
  Terminal as IconTerminal,
  Server as IconServer,
  CheckCircle as IconCheckCircle,
  XCircle as IconXCircle,
  Minus as IconMinus,
  Send as IconSend,
  Filter as IconFilter,
} from '@geist-ui/icons';
