// Lucide icons, re-exported so the rest of the app can keep importing them as
// `Icon*` (no per-file imports). Lucide's icon set is stroke=currentColor,
// 24x24 viewBox, and accepts the same `size` / `className` props the old Geist
// icons did, so existing usages (`<IconX size={16} />`) work unchanged.
export {
  Home as IconHome,
  BarChart3 as IconBarChart,
  Database as IconDatabase,
  Settings as IconSettings,
  Users as IconUsers,
  Search as IconSearch,
  Globe as IconGlobe,
  Sun as IconSun,
  Moon as IconMoon,
  LogOut as IconLogOut,
  Check as IconCheck,
  X as IconX,
  ChevronDown as IconChevronDown,
  Plus as IconPlus,
  ExternalLink as IconExternalLink,
  Copy as IconCopy,
  Trash2 as IconTrash2,
  Pencil as IconEdit2,
  Info as IconInfo,
  TriangleAlert as IconAlertTriangle,
  RefreshCw as IconRefreshCw,
  MoreVertical as IconMoreVertical,
  ArrowUpRight as IconArrowUpRight,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  Link as IconLink,
  Mail as IconMail,
  Terminal as IconTerminal,
  Server as IconServer,
  Shield as IconShield,
  CircleCheck as IconCheckCircle,
  CircleX as IconXCircle,
  Minus as IconMinus,
  Send as IconSend,
  Filter as IconFilter,
} from 'lucide-react';
