'use client';

import { useCallback, useEffect, useState } from 'react';
import { Activity, Pencil, Plus, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useTranslations } from 'next-intl';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { createProviderAccount, fetchProviderAccounts, testProviderAccountModel, updateProviderAccount } from '@/lib/api';
import type { ProviderAccount } from '@/lib/types';

const CATALOG: Record<string, Array<{ id: string; name: string }>> = {
  'openai.responses.v1': [{ id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol' }, { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra' }, { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna' }],
  'openai.chat_completions.v1': [{ id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol' }, { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra' }, { id: 'gpt-5.6-luna', name: 'GPT-5.6 Luna' }],
  'anthropic.messages.v1': [{ id: 'claude-opus-4-1-20250805', name: 'Claude Opus 4.1' }, { id: 'claude-sonnet-4-20250514', name: 'Claude Sonnet 4' }],
};
const DEFAULT_URL: Record<string, string> = { 'openai.responses.v1': 'https://api.openai.com/v1', 'openai.chat_completions.v1': 'https://api.openai.com/v1', 'anthropic.messages.v1': 'https://api.anthropic.com' };

export default function ModelsPage() {
  const t = useTranslations('admin'); const tc = useTranslations('common'); const [accounts, setAccounts] = useState<ProviderAccount[]>([]); const [editing, setEditing] = useState<ProviderAccount | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setAccounts(await fetchProviderAccounts()); setError(''); } catch (cause) { setError(String(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <main className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="page-title">{t('providerAccounts')}</h1><p className="page-subtitle">{t('modelsSubtitle')}</p></div><div className="flex gap-2"><Button size="icon" variant="outline" title={tc('refresh')} aria-label={tc('refresh')} onClick={() => void load()}><RefreshCw size={16} /></Button><Button size="sm" onClick={() => { setEditing(null); setOpen(true); }}><Plus size={16} />{t('addAccount')}</Button></div></header>{error ? <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}<section className="space-y-3">{accounts.map((account) => <article key={account.id} className="border-b pb-5 last:border-0"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{account.name}</h2><p className="mono text-xs text-muted-foreground">{account.protocol_id} | {account.base_url}</p></div><Button size="icon" variant="ghost" title={t('editAccount')} aria-label={t('editAccount')} onClick={() => { setEditing(account); setOpen(true); }}><Pencil size={16} /></Button></div><div className="mt-3 overflow-x-auto border"><table className="table"><thead><tr><th>{t('providerModel')}</th><th>{t('availability')}</th><th>{t('state')}</th><th /></tr></thead><tbody>{account.models.map((model) => <tr key={model.id}><td><span className="font-medium">{model.display_name}</span><span className="ml-2 mono text-xs text-muted-foreground">{model.provider_model_id}</span></td><td>{model.availability_state}</td><td>{model.state}</td><td><Button size="icon" variant="ghost" disabled={model.state !== 'active'} onClick={() => void testProviderAccountModel(account.id, model.id).then(load).catch((cause) => toast.error(String(cause)))}><Activity size={16} /></Button></td></tr>)}</tbody></table></div></article>)}</section><AccountDialog open={open} account={editing} onOpenChange={setOpen} onSaved={load} /></main>;
}

function AccountDialog({ open, account, onOpenChange, onSaved }: { open: boolean; account: ProviderAccount | null; onOpenChange: (value: boolean) => void; onSaved: () => Promise<void> }) {
  const tc = useTranslations('common'); const t = useTranslations('admin'); const [name, setName] = useState(''); const [protocolId, setProtocolId] = useState('openai.responses.v1'); const [baseUrl, setBaseUrl] = useState(DEFAULT_URL['openai.responses.v1']); const [credential, setCredential] = useState(''); const [models, setModels] = useState<string[]>([]);
  useEffect(() => { if (!open) return; const protocol = account?.protocol_id ?? 'openai.responses.v1'; setName(account?.name ?? ''); setProtocolId(protocol); setBaseUrl(account?.base_url ?? DEFAULT_URL[protocol]); setCredential(''); setModels(account?.models.filter((model) => model.state === 'active').map((model) => model.provider_model_id) ?? []); }, [account, open]);
  function changeProtocol(value: string) { setProtocolId(value); setBaseUrl(DEFAULT_URL[value]); setModels([]); }
  async function save() { const input = { name, protocol_id: protocolId, base_url: baseUrl, ...(credential ? { credential } : {}), model_ids: models }; try { if (account) await updateProviderAccount(account.id, input); else await createProviderAccount(input); onOpenChange(false); await onSaved(); } catch (cause) { toast.error(String(cause)); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{account ? t('editAccount') : t('addAccount')}</DialogTitle></DialogHeader><div className="space-y-3"><Input placeholder={t('accountName')} value={name} onChange={(event) => setName(event.target.value)} /><Select value={protocolId} onChange={(event) => changeProtocol(event.target.value)}><option value="openai.responses.v1">OpenAI Responses</option><option value="openai.chat_completions.v1">OpenAI Chat Completions</option><option value="anthropic.messages.v1">Anthropic Messages</option></Select><Input className="mono" placeholder={t('httpsBaseUrl')} value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /><Input type="password" placeholder={account ? t('credentialOptional') : t('credential')} value={credential} onChange={(event) => setCredential(event.target.value)} /><div className="max-h-52 overflow-y-auto border">{CATALOG[protocolId].map((model) => <label key={model.id} className="flex items-center gap-3 border-b px-3 py-2 text-sm"><input type="checkbox" checked={models.includes(model.id)} onChange={(event) => setModels((current) => event.target.checked ? [...new Set([...current, model.id])] : current.filter((id) => id !== model.id))} />{model.name}<span className="mono text-xs text-muted-foreground">{model.id}</span></label>)}</div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>{tc('cancel')}</Button><Button variant="primary" disabled={!name || !baseUrl || !models.length || (!account && !credential)} onClick={() => void save()}>{tc('save')}</Button></DialogFooter></DialogContent></Dialog>;
}
