"""Reviewed, server-owned operational limits.

These values are intentionally code constants. They describe the product's
execution envelope, not deployment topology or credentials, so exposing each
one as an environment variable would create unsupported runtime variants.
"""

from __future__ import annotations

API_RATE_LIMIT_PER_MINUTE = 600
AUTH_TOKEN_TTL_SECONDS = 86_400

KAFKA_SUBSCRIPTION_REFRESH_SECONDS = 5.0
KAFKA_TOPIC_VALIDATION_TIMEOUT_SECONDS = 10.0
KAFKA_BATCH_MAX_RECORDS = 100
KAFKA_CONSUMER_GROUP_ID = "lode-consumer"
KAFKA_DEAD_LETTER_TOPIC = "lode.dlq"
KAFKA_UNASSIGNED_TOPIC = "lode.unassigned"

WORKER_LEASE_TTL_SECONDS = 300
WORKER_POLL_INTERVAL_SECONDS = 1.0
JOB_MAX_ATTEMPTS = 5
JOB_BASE_RETRY_DELAY_SECONDS = 5.0

SOURCE_MAX_FILES = 8
SOURCE_MAX_BYTES = 80_000
SOURCE_SNIPPET_LINES = 12
SOURCE_GIT_TIMEOUT_SECONDS = 60.0

DATABASE_LOCK_TIMEOUT_SECONDS = 3.0
EVIDENCE_AUTHORIZATION_TTL_SECONDS = 60
LOGQL_PARSER_NODE = "node"
LOGQL_PARSER_TIMEOUT_SECONDS = 2.0

LLM_MAX_RETRIES = 3
LLM_RETRY_BASE_DELAY_SECONDS = 0.5
LLM_REQUEST_TIMEOUT_SECONDS = 120.0
LLM_PROBE_TIMEOUT_SECONDS = 30.0

AI_PROVIDER_MAX_RESPONSE_BYTES = 2 * 1024 * 1024
